# Generated by Django 4.0.5 on 2022-08-15 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Foodiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipr',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='Foodiz_app.profile'),
        ),
    ]
