# Generated by Django 4.0.5 on 2022-08-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodiz_app', '0003_category_ingredient_alter_recipe_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
